<?xml version="1.0" encoding="UTF-8"?>
<plist version="1.0">
<dict>
	<key>name</key>
	<string>MyLanguage</string>
	<key>scopeName</key>
	<string>source.mylanguage</string>
	<key>fileTypes</key>
	<array>
		<string>.mylang</string>
	</array>
	<key>patterns</key>
	<array>
		<!-- Keywords -->
		<dict>
			<key>match</key>
			<string>(print|printRaw|write|writeRaw|group|object|image|label|font|move|scale|color|var|varRaw|textbox|multiLine|varInput|varSet|varEquals|varAddText|list|listRaw|writeToFile|sound|playFile|button|buttonClick)\b</string>
			<key>name</key>
			<string>keyword.control.mylanguage</string>
		</dict>
		<!-- Loops and Control Statements -->
		<dict>
			<key>match</key>
			<string>(loop|end|:|if|endIf)\b</string>
			<key>name</key>
			<string>keyword.control.loop.mylanguage</string>
		</dict>
		<!-- One-Word Keywords -->
		<dict>
			<key>match</key>
			<string>(consoleClear|await|endBuild)\b</string>
			<key>name</key>
			<string>keyword.control.oneword.mylanguage</string>
		</dict>
		<!-- Afters -->
		<dict>
			<key>match</key>
			<string>(~\/|\/|\*|\-|\+|!|\\_|\\n|\\!|&gt;|&lt;|ReadFile|change|abs|rel|new|relative|absolute|AwaitKeyInput|KeyDown|KeyInput|ConsoleInput|Random|MousePosition|MouseClick|FromList|Key|Console|StickKey|await|AwaitKey|IntersectsWith|bold|italic|strikeout|underline|regular|FromTextBox|input|now)\b</string>
			<key>name</key>
			<string>keyword.control.after.mylanguage</string>
		</dict>
		<!-- Comments -->
		<dict>
			<key>match</key>
			<string>(\/\/.*$)</string>
			<key>name</key>
			<string>comment.line.mylanguage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\/\/\/.*$)</string>
			<key>name</key>
			<string>comment.block.documentation.mylanguage</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(#.*$)</string>
			<key>name</key>
			<string>comment.line.hashtag.mylanguage</string>
		</dict>
	</array>
</dict>
</plist>